# Generated by Django 4.2.1 on 2023-08-05 09:58

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_booking_expiration_date'),
        ('account', '0010_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='compound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.compound'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='', null=True, upload_to=account.models.upload_to),
        ),
    ]
