# Generated by Django 4.2.1 on 2023-07-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_type'),
        ),
    ]
