# Generated by Django 4.2.1 on 2023-07-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_accomodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='has_disable',
            field=models.BooleanField(default=True),
        ),
    ]
