# Generated by Django 4.2.1 on 2023-07-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_compound_has_disable'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='has_disable',
            field=models.BooleanField(default=True),
        ),
    ]
