# Generated by Django 4.2.1 on 2023-08-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_booking_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
