# Generated by Django 4.2.1 on 2023-08-05 13:24

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_booking_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
    ]
