# Generated by Django 4.2.1 on 2023-08-05 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_image'),
        ('client', '0007_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.transaction'),
        ),
    ]
