# Generated by Django 4.2.1 on 2023-08-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_booking_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='access_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
